apiVersion: v1
kind: Service
metadata:
  name: ms-auth
spec:
  selector:
    app: ms-auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # Service type (ClusterIP, NodePort, LoadBalancer)
