version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1
      DB_NAME: auth

  db:
    image: postgres:15
    ports:
      - '5532:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: auth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
