apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration-container
          image: ms-auth:latest
          imagePullPolicy: Never
          command: ['npm', 'run', 'migration:run']
          env:
            - name: DB_HOST
              value: 'pg-service'
            - name: DB_PORT
              value: '5532'
            - name: DB_USER
              value: 'postgres'
            - name: DB_PASSWORD
              value: '1'
            - name: DB_NAME
              value: 'auth'
      restartPolicy: Never
  backoffLimit: 4
