apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5532
      targetPort: 5432
  type: LoadBalancer # Service type (ClusterIP, NodePort, LoadBalancer)
